name: CI

on: [push]

jobs:
  ecto31:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecto_network_test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        env:
          LOCKFILE: mix.lock.ecto31
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run all tests
        env:
          LOCKFILE: mix.lock.ecto31
          DATABASE_URL: "ecto://postgres:postgres@postgres/ecto_network_test"
        run: mix test

  # ecto32:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: elixir:1.9.1-slim
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install dependencies
  #       run: |
  #         mix local.rebar --force
  #         mix local.hex --force
  #         LOCKFILE=mix.lock mix deps.get
  #     - name: Run all tests
  #       run: mix test
